title: Natural Language Reasoning and Structured Explanations Workshop
description: Natural Language Reasoning and Structured Explanations Workshop
  ---
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
include: ['_pages']
ga_id: UA-144588579-1
